"""Turn curation results into the live gallery.
   Reads tools/curation.json  ->  copies kept optimized images into assets/img/
   and writes data/images.json (with a 'featured' subset for the 3D gallery + full archive).

   curation.json format: {"all":[...], "kept":[...]} or a bare list of items, each:
   { stem, keep, onSkin, category, title, placement, palette, quality }
"""
import os, json, shutil

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
OPT  = os.path.join(ROOT, "tools", "_opt")
IMG  = os.path.join(ROOT, "assets", "img")
os.makedirs(IMG, exist_ok=True)

with open(os.path.join(ROOT, "tools", "curation.json"), encoding="utf-8") as f:
    data = json.load(f)
items = data.get("kept") if isinstance(data, dict) else data
if items is None:
    items = [x for x in data.get("all", []) if x.get("keep")]

# keep only those we actually have an optimized file for
clean = []
for it in items:
    stem = it["stem"]
    src = os.path.join(OPT, stem + ".jpg")
    if not os.path.exists(src):
        continue
    clean.append(it)

# de-dupe by stem
seen, uniq = set(), []
for it in clean:
    if it["stem"] in seen:
        continue
    seen.add(it["stem"]); uniq.append(it)
clean = uniq

# copy images into assets/img
for it in clean:
    shutil.copyfile(os.path.join(OPT, it["stem"] + ".jpg"), os.path.join(IMG, it["stem"] + ".jpg"))

# newest first (IG ids are ascending over time)
def key(it):
    base = it["stem"].split("_")[0]
    return int(base) if base.isdigit() else 0
clean.sort(key=key, reverse=True)

# choose a balanced, high-quality featured set for the 3D gallery (~42)
FEATURED_MAX = 42
PER_CAT_CAP = 8
strong = [x for x in clean if x.get("quality", 0) >= 4] or [x for x in clean if x.get("quality", 0) >= 3]
by_cat, featured = {}, []
for it in sorted(strong, key=lambda x: x.get("quality", 0), reverse=True):
    c = it.get("category", "Other")
    if by_cat.get(c, 0) >= PER_CAT_CAP:
        continue
    by_cat[c] = by_cat.get(c, 0) + 1
    featured.append(it["stem"])
    if len(featured) >= FEATURED_MAX:
        break
featured_set = set(featured)

def to_item(it):
    return {
        "id": it["stem"],
        "src": f"./assets/img/{it['stem']}.jpg",
        "category": it.get("category", "Other"),
        "title": it.get("title", ""),
        "placement": it.get("placement", ""),
        "palette": it.get("palette", "black"),
        "onSkin": it.get("onSkin", True),
        "quality": it.get("quality", 3),
        "featured": it["stem"] in featured_set
    }

out = {
    "_note": "Generated by tools/build_manifest.py from curated Instagram photos.",
    "count": len(clean),
    "featuredCount": len(featured_set),
    "items": [to_item(it) for it in clean]
}
with open(os.path.join(ROOT, "data", "images.json"), "w", encoding="utf-8") as f:
    json.dump(out, f, ensure_ascii=False, indent=2)

cats = {}
for it in clean:
    cats[it.get("category", "Other")] = cats.get(it.get("category", "Other"), 0) + 1
print(f"kept {len(clean)} images -> assets/img/  | featured {len(featured_set)}")
print("by category:", json.dumps(cats, ensure_ascii=False))
